### ISSUE TITLE
How to deal with gap analysis? Ned clear definition for "gap analysis

### ISSUE THREAD

**Issue by chachamimm** [w3c/wot-usecases#266] opened 2024-01-31 05:06 UTC
McCool: we need a document on the current features.
... I agree we should not accept proposals which are already covered.
... Btw, I think user stories are good way to see the gaps also see issue 261 also
... https://github.com/w3c/wot-usecases/issues/261
kaz: we need to define "gap analysis" a bit more
... user story is important but it's already required for the use case definition phase as the starting point
... my understanding on what Mizushima-san meant by "gap analysis" is evaluating if the requirements extracted from the use cases are already covered by the existing WoT standards or not
... but we still need to clarify what we mean by "gap analysis"

**Comment by egekorkan** [comment] 2024-01-31 13:07
Duplicate of #267, closing

**Closed by egekorkan** 2024-01-31 13:07 UTC
Labels: Process
